[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirect all routes to index.html (for React Router SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
